import * as fs from 'fs';
import * as path from 'path';

const folder_name_extension_settings = "extension-always-learn";
const file_name_extension_settings = "git-shortcuts.json";
const file_name_extension_error_log = "errors-git-shortcuts.log";

export interface ExtConfig {
    'info': string;
    'main-branch-name': string;
    'local-branch-name': string;
    'git-exe': string;
    'bash-exe': string;
    'language': string;
}

export const DEFAULT_CONFIG: ExtConfig = {
    'info': 'this file is auto-generated by the extension. You can edit/delete it to change default values for branch names and git/bash executable paths.',
    'main-branch-name': 'main',
    'local-branch-name': 'temporary-branch',
    'git-exe': 'C:\\Program Files\\Git\\cmd\\git.exe',
    'bash-exe': 'C:\\Program Files\\Git\\bin\\bash.exe',
    'language': 'en',
};

export function logError(workspacePath: string, context: string, err: unknown): void {
    try {
        const logPath = path.join(workspacePath, `.${folder_name_extension_settings}`, file_name_extension_error_log);
        fs.mkdirSync(path.dirname(logPath), { recursive: true });
        const message = err instanceof Error
            ? `${err.message}\n${err.stack ?? ''}`
            : String(err);
        const entry = `[${new Date().toISOString()}] [${context}]\n${message}\n\n`;
        fs.appendFileSync(logPath, entry, 'utf8');
    } catch { /* ignore log write failures */ }
}

export function getConfigPath(workspacePath: string): string {
    return path.join(workspacePath, `.${folder_name_extension_settings}`, file_name_extension_settings);
}

export function loadOrCreateConfig(workspacePath: string): ExtConfig {
    const configPath = getConfigPath(workspacePath);
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    if (!fs.existsSync(configPath)) {
        fs.writeFileSync(configPath, JSON.stringify(DEFAULT_CONFIG, null, 4), 'utf8');
        const gitignorePath = path.join(workspacePath, '.gitignore');
        if (fs.existsSync(gitignorePath)) {
            const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8');
            if (!gitignoreContent.includes('.extension-always-learn')) {
                fs.appendFileSync(gitignorePath, `\n# AlwaysLearn Extension\n.${folder_name_extension_settings}/\n`, 'utf8');
            }
        }
        return { ...DEFAULT_CONFIG };
    }
    try {
        return { ...DEFAULT_CONFIG, ...JSON.parse(fs.readFileSync(configPath, 'utf8')) };
    } catch (err) {
        logError(workspacePath, 'loadOrCreateConfig', err);
        return { ...DEFAULT_CONFIG };
    }
}

export function saveConfig(workspacePath: string, key: keyof ExtConfig, value: string): void {
    const config = loadOrCreateConfig(workspacePath);
    config[key] = value;
    fs.writeFileSync(getConfigPath(workspacePath), JSON.stringify(config, null, 4), 'utf8');
}
